version: '3'
services:
  db:
    image: mysql:5.7
    container_name: some-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw

  app:
    build: ./php
    container_name: 'php'
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PASS=my-secret-pw