version: '3'
services:
  app:
    build: ./php
    container_name: php
    volumes:
      - ./application:/var/www/html

  web:
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro