version: '2'
services:
  web:
    image: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
